---
  - name: Converge
    hosts: all
    tasks:
      - name: "Include ansible role"
        include_role:
          name: "ansible-role-bashrc"
          apply:
            become: true
        vars:
          systemwide: true
          github_user: "ckaserer"
          github_token: "{{ lookup('env','GITHUB_TOKEN') }}"
...