---
  - name: Find latest bashrc release
    uri:
      url: https://api.github.com/repos/ckaserer/bashrc/releases/latest
      return_content: true
      user: "{{ github_user }}"
      password: "{{ github_token }}"
      force_basic_auth: "{{ true 
        if 
          github_token is defined and 
          github_user is defined and 
          github_token != '' and
          github_user != ''
        else 
          false }}"
    register: json_reponse

  - name: Get latest bashrc release tar.gz
    get_url:
      url: "{{ json_reponse.json.tarball_url }}"
      dest: /tmp/bashrc.tar.gz
      username: "{{ github_user }}"
      password: "{{ github_token }}"
      force_basic_auth: "{{ true 
      if 
        github_token is defined and 
        github_user is defined and 
        github_token != '' and
        github_user != ''
      else 
        false }}"

  - name: Set bashrc location
    set_fact:
      bashrc_folder: "{{ '/opt/ckaserer-bashrc' if systemwide else '~/.ckaserer-bashrc' }}"

  - name: Bashrc folder location
    debug:
      var: bashrc_folder
      verbosity: 2

  - name: Create bashrc folder
    file:
      path: "{{ bashrc_folder }}"
      state: directory
      mode: '0755'

  - name: Unarchive bashrc.tar.gz
    unarchive:
      src: /tmp/bashrc.tar.gz
      dest: "{{ bashrc_folder }}"
      remote_src: yes
      extra_opts: [--strip-components=1]
      mode: '0755'

  - name: Add bashrc to current user
    blockinfile:
      path: ~/.bashrc
      block: |
        if [ -f {{ bashrc_folder }}/bashrc ]; then
          . {{ bashrc_folder }}/bashrc
        fi
    when: not systemwide

  - name: Add bashrc globally
    blockinfile:
      path: "/etc/bashrc"
      block: |
          if [ -f {{ bashrc_folder }}/bashrc ]; then
          . {{ bashrc_folder }}/bashrc
          fi
    when: systemwide
...