---
  - name: Converge
    hosts: all
    tasks:
      - name: "Include ansible-role-bashrc"
        include_role:
          name: "ansible-role-bashrc"
          apply:
            become: true
        vars:
          bashrc_global: true
...