---
  - name: Verify
    hosts: all
    become: true
    tasks:
      - name: Check that ~/.custom-bashrc/bashrc exists
        stat:
          path: ~/.custom-bashrc/bashrc
        register: verify_custom_bashrc
        failed_when: not verify_custom_bashrc.stat.exists

      - name: Check that global bashrc does not exist
        stat:
          path: /opt/bashrc/bashrc
        register: verify_global_bashrc
        failed_when: verify_global_bashrc.stat.exists

      - name: Check that custom bashrc is present in ~/.bashrc
        blockinfile:
          path: ~/.bashrc
          block: |
            if [ -f ~/.custom-bashrc/bashrc ]; then
              . ~/.custom-bashrc/bashrc
            fi
        check_mode: yes
        register: verify_current_user_bashrc
        failed_when: verify_current_user_bashrc.changed
      
      - name: Check that /etc/bashrc does not contain /opt/bashrc/bashrc
        blockinfile:
          path: /etc/bashrc
          block: |
            if [ -f /opt/bashrc/bashrc ]; then
            . /opt/bashrc/bashrc
            fi
        check_mode: yes
        register: verify_etc_bashrc
        failed_when: not verify_etc_bashrc.changed
...