---
  - name: Verify
    hosts: all
    become: true
    tasks:
      - name: Check that ~/.ckaserer-bashrc/bashrc exists
        stat:
          path: ~/.ckaserer-bashrc/bashrc
        register: verify_bashrc_location_for_user
        failed_when: not verify_bashrc_location_for_user.stat.exists

      - name: Check that global bashrc does not exist
        stat:
          path: /opt/bashrc/bashrc
        register: verify_systemwide_bashrc_location
        failed_when: verify_systemwide_bashrc_location.stat.exists

      - name: Check that custom bashrc is present in ~/.bashrc
        blockinfile:
          path: ~/.bashrc
          block: |
            if [ -f ~/.ckaserer-bashrc/bashrc ]; then
              . ~/.ckaserer-bashrc/bashrc
            fi
        check_mode: yes
        register: verify_user_bashrc
        failed_when: verify_user_bashrc.changed

      - name: Check that /etc/bashrc does not contain /opt/bashrc/bashrc
        blockinfile:
          path: /etc/bashrc
          block: |
            if [ -f /opt/bashrc/bashrc ]; then
            . /opt/bashrc/bashrc
            fi
        check_mode: yes
        register: verify_systemwide_bashrc
        failed_when: not verify_systemwide_bashrc.changed
...